#!/usr/bin/python3

#Task 34
vowels = 'аоуыэяёюие'
poem = input('Введите стих: ').split()
print(poem)

res = list(map(lambda word: len(list(filter(lambda i: i in vowels, word))), poem))
print(res)

if len(list(filter(lambda x: x== sum(res)/len(res), res))) == len(res):  # Если все числа в массиве равны, то они все будут равны их среднеарифметическому
    print('Парам пам-пам')
else:
   print('Пам парам') 


#task 36
def print_operation_table(operation, num_rows=6, num_columns=6):

    a = [[0] * (num_columns+1) for i in range(num_rows+1)]

    for i in range(1, len(a)):              # не с 0 потому что нулевые столбец и строка будут все нулями,
        for j in range(1, len(a[i])):       # а в случае передачи через лямбду деления будет ошибка деления на ноль
            a[i][j] = operation(i,j)
            print(a[i][j], end=' ')
        print()

print_operation_table(lambda x, y: x+y)
print()
print_operation_table(lambda x, y: x/y)
