#!/bin/python3
#Task 1

def power(param1,param2):
    if (param2 == 1):
        return(param2)
    if (param2 != 1):
        return(param1 * power(param1,param2 - 1))
par1 = int(input("Enter the number:"))
par2 = int(input("Enter the power of number:"))
print(power(par1,par2))

#Task 2

a = int(input("Enter the first number:"))
b = int(input("Enter the first number:"))

def summa(a,b):
    if b == 0:
        return a
    return summa(a+1, b-1)
print(summa(a,b))